### ISSUE TITLE
PythonAPI fails to download annotations

### ISSUE THREAD

**Issue by matthias-k** [NUS-VIP/salicon-api#1]
If I run `python setup.py install` in the PythonAPI directory, it fails after the questions "Do you want to download train split for fixations annotations [524MB] under ./annotations? [Y/n]"  with a 404 HTTP error. The URL in question seems to be
[this one](https://dl.dropboxusercontent.com/u/3777195/salicon/2015_r1/annotation/fixations_train2015r1.json).

**Comment by mjiang** [comment]
The download links have been fixed.
