### ISSUE TITLE
Data doesn't exist on dropbox anymore

### ISSUE THREAD

**Issue by alykhantejani** [NUS-VIP/salicon-api#3]
Hi, 

I tried to use the setup script to download the training zip file located at `https://dl.dropboxusercontent.com/u/3777195/salicon-dataset/2015r1/train.zip`. However, this no longer seems to exist

**Comment by mjiang** [comment]
The download links are fixed. Alternatively, you may download the data from our project [website](http://salicon.net/download/).

**Comment by alykhantejani** [comment]
Thanks
